return {
    useTarget = false,
    debugPoly = false,
    enableFreeUseBuy = true, -- Allows players to buy from NPC shops
    requestModelTimeout = 5000, -- load model timeout for oxlib
    enableTestDrive = true,

    finance = {
        enable = true, -- Enables the financing system. Turning this off does not affect already financed vehicles
        commissionRate = 0.05, -- Percent that goes to sales person from a finance sale 5%
        zone = vec3(-29.53, -1103.67, 26.42), -- Where the finance menu is located
    },

    -- For the configuration below, it would first look for the vehicle in models. If not found, it would check for the category in categories. If the category is also not found, it would default to the default settings.
    default = 'pdm',

    categories = {
        boats = 'boats',
        air = 'air',
        -- super = {'pdm', 'luxury'},
    },

    models = {
        -- zentorno = {'pdm', 'luxury'},
        
        oppressor = 'luxury',
        --- Sports
        alpha = 'luxury',
        banshee = 'luxury',
        bestiagts = 'luxury',
        buffalo = 'luxury',
        buffalo2 = 'luxury',
        carbonizzare = 'luxury',
        comet2 = 'luxury',
        comet3 = 'luxury',
        comet4 = 'luxury',
        comet5 = 'luxury',
        coquette = 'luxury',
        coquette4 = 'luxury',
        drafter = 'luxury',
        deveste = 'luxury',
        elegy = 'luxury',
        elegy2 = 'luxury',
        feltzer2 = 'luxury',
        flashgt = 'luxury',
        furoregt = 'luxury',
        gb200 = 'luxury',
        komoda = 'luxury',
        imorgon = 'luxury',
        italigto = 'luxury',
        jugular = 'luxury',
        jester = 'luxury',
        jester2 = 'luxury',
        jester3 = 'luxury',
        khamelion = 'luxury',
        kuruma = 'luxury',
        kuruma2 = 'luxury',
        locust = 'luxury',
        lynx = 'luxury',
        massacro = 'luxury',
        massacro2 = 'luxury',
        neo = 'luxury',
        neon = 'luxury',
        ninef = 'luxury',
        ninef2 = 'luxury',
        omnis = 'luxury',
        paragon = 'luxury',
        pariah = 'luxury',
        penumbra = 'luxury',
        penumbra2 = 'luxury',
        rapidgt = 'luxury',
        rapidgt2 = 'luxury',
        raptor = 'luxury',
        revolter = 'luxury',
        ruston = 'luxury',
        schafter3 = 'luxury',
        schafter4 = 'luxury',
        schlagen = 'luxury',
        schwarzer = 'luxury',
        seven70 = 'luxury',
        specter = 'luxury',
        streiter = 'luxury',
        sugoi = 'luxury',
        sultan = 'luxury',
        sultan2 = 'luxury',
        surano = 'luxury',
        tropos = 'luxury',
        verlierer2 = 'luxury',
        vstr = 'luxury',
        italirsx = 'luxury',
        zr350 = 'luxury',
        calico = 'luxury',
        futo2 = 'luxury',
        euros = 'luxury',
        jester4 = 'luxury',
        remus = 'luxury',
        comet6 = 'luxury',
        growler = 'luxury',
        vectre = 'luxury',
        cypher = 'luxury',
        sultan3 = 'luxury',
        rt3000 = 'luxury',

        --- Sports Classic
       
        cheetah2 = 'luxury',
        --- Super
        adder = 'luxury',
        autarch = 'luxury',
        banshee2 = 'luxury',
        bullet = 'luxury',
        cheetah = 'luxury',
        cyclone = 'luxury',
        entity2 = 'luxury',
        entityxf = 'luxury',
        emerus = 'luxury',
        fmj = 'luxury',
        furia = 'luxury',
        gp1 = 'luxury',
        infernus = 'luxury',
        italigtb = 'luxury',
        italigtb2 = 'luxury',
        krieger = 'luxury',
        le7b = 'luxury',
        nero = 'luxury',
        nero2 = 'luxury',
        osiris = 'luxury',
        penetrator = 'luxury',
        pfister811 = 'luxury',
        prototipo = 'luxury',
        reaper = 'luxury',
        s80 = 'luxury',
        sc1 = 'luxury',
        sheava = 'luxury',
        sultanrs = 'luxury',
        t20 = 'luxury',
        taipan = 'luxury',
        tempesta = 'luxury',
        tezeract = 'luxury',
        thrax = 'luxury',
        tigon = 'luxury',
        turismor = 'luxury',
        tyrant = 'luxury',
        tyrus = 'luxury',
        vacca = 'luxury',
        vagner = 'luxury',
        visione = 'luxury',
        voltic = 'luxury',
        voltic2 = 'luxury',
        xa21 = 'luxury',
        zentorno = 'luxury',
        zorrusso = 'luxury',

        --- Boats
        squalo = 'boats',
        marquis = 'boats',
        seashark = 'boats',
        seashark2 = 'boats',
        seashark3 = 'boats',
        jetmax = 'boats',
        tropic = 'boats',
        tropic2 = 'boats',
        dinghy = 'boats',
        dinghy2 = 'boats',
        dinghy3 = 'boats',
        dinghy4 = 'boats',
        suntrap = 'boats',
        speeder = 'boats',
        speeder2 = 'boats',
        longfin = 'boats',
        toro = 'boats',
        toro2 = 'boats',

        --- Helicopters
        buzzard2 = 'air',
        frogger = 'air',
        frogger2 = 'air',
        maverick = 'air',
        swift = 'air',
        swift2 = 'air',
        seasparrow = 'air',
        seasparrow2 = 'air',
        seasparrow3 = 'air',
        supervolito = 'air',
        supervolito2 = 'air',
        volatus = 'air',
        havok = 'air',

        --- Planes
        duster = 'air',
        luxor = 'air',
        luxor2 = 'air',
        stunt = 'air',
        mammatus = 'air',
        velum = 'air',
        velum2 = 'air',
        shamal = 'air',
        vestra = 'air',
        dodo = 'air',
        howard = 'air',
        alphaz1 = 'air',
        nimbus = 'air',
        conada = 'air',
        corsita = 'luxury',
        lm87 = 'luxury',
        omnisegt = 'luxury',
        sentinel4 = 'luxury',
        sm722 = 'luxury',
        tenf = 'luxury',
        tenf2 = 'luxury',
        torero2 = 'luxury',

    },
}
